---
- name: Listen for events on alertmanager
  hosts: localhost

  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8080
        data_host_path: ""
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8080

  rules:
    - name: alertmanager
      condition: event.alert is defined
      action:
        run_job_template:
          name: do-something.yml
#          inventory: inventory.yml
          var_root: payload
#          organization: Default
#          job_args:
#            extra_vars: {}
#            env:
#              CONTROLLER_VERIFY_SSL: "false"
    - name: webhook
      condition: event.payload.message != ""
      action:
        run_job_template:
          name: do-something.yml
#          inventory: inventory.yml
          var_root: payload
#          organization: Default
#          job_args:
#            extra_vars: {}
#            env:
#              CONTROLLER_VERIFY_SSL: "false"
